### ISSUE TITLE
[Optional Request] Cycle window.

### ISSUE THREAD

**Issue by lidgnulinux** [mdepx/stage#2]
Hello, I forked your compositor [here](https://gitlab.com/lidgl/stage-next), I just add some stuffs I need. BTW, do you have a clue to cycle windows ? I tried to use an example from tinywl but end up crashing the compositor. I have a plan to use it as daily drive. Thanks.

**Comment by lidgnulinux** [comment]
Okay, I think I will figure it out.

**Comment by bukinr** [comment]
Good. You can submit some pull requests if you want (but split functionality to individual commits for each feature).
What I want to look at is region-screenshot ability, similar to what Firefox provides when you press Ctrl+shift+s, but for entire screen, not just browser window. If you have ideas let me know

**Comment by lidgnulinux** [comment]
> What I want to look at is region-screenshot ability

Yeah, currently slurp still not work on stage.

> If you have ideas let me know

How about this :
- we use transparent "dummy window" that we can resize into our desired screenshot region.
- then we get the geometry of that window , need to make a function for that (print it to stdout).
- bring the window to the bottom (you can check my `send_lower` function).
- get the geometry info from stdout and feed it to `grim`.

**Comment by lidgnulinux** [comment]
Kind of give up on this issue haha, can't figure out how to list the windows first.

**Comment by lidgnulinux** [comment]
Aaah, it's too early to give up. I seem can mimic "cycle window" but only when all windows are maximized.

**Comment by lidgnulinux** [comment]
I just found a simple function to cycle window. I just made a [commit](https://gitlab.com/lidgld/stage-next/-/commit/4d6f936d68c3cf5f19e973b1242452efdb6de76c).

**Comment by lidgnulinux** [comment]
Fix cycle windows : https://gitlab.com/lidgl/stage-next/-/commits/main
