### ISSUE TITLE
Popup management.

### ISSUE THREAD

**Issue by lidgnulinux** [mdepx/stage#5]
Hello, it's me again.
Sorry to bother you again, sir. Is there a plan to adjust popup management on stage ? I just realized when I click on firefox bookmark menu and bookmark list goes out of screen. I'm trying to tinkering it using dwl as reference but it always goes wrong. Thanks.

Here is the screenshot.

![20230721_08h46m42s_grim](https://github.com/mdepx/stage/assets/99301306/f64d5f31-3d58-42bb-8c75-26dee7b5d5ca)

**Comment by lidgnulinux** [comment]
Perhaps, [this](https://github.com/godalming123/tinytile/commit/a7eedb8d740adcad993951ed01db6c9136076c6c) is related.

**Comment by bukinr** [comment]
I am trying to reproduce but no lack yet. When I open bookmarks they appear normally in my firefox under FreeBSD.

**Comment by ahmadraniri** [comment]
Hello, sorry for commenting using alternate account. Have you tried right click at the most right of the screen (on firefox)? I'm sure you will find the popup goes off the screen.

**Comment by lidgnulinux** [comment]
I managed to implement a simple popup unconstran feature. I will close this issue. Thanks.
